spring.application.name=microservicio-usuarios-backend


server.port=8084

# ORACLE DB
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521/XEPDB1
spring.datasource.username=APP_ADMIN
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


# 🔥 IMPORTANTE (FIX ORACLE SCHEMA)
spring.jpa.properties.hibernate.default_schema=APP_ADMIN
